import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DataProvider } from "@/context/DataContext";
import { loadAppData } from "@/lib/data";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const fetcheddata = await loadAppData();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DataProvider
          value={{
            countries: fetcheddata.countries,
            countryprovinces: fetcheddata.countryprovinces,
            paths: fetcheddata.paths,
            emptylands: fetcheddata.emptylands,
            areapaths: fetcheddata.areapaths,
            countryoutlines: fetcheddata.countryoutlines,
            terraincolors: fetcheddata.terraincolors,
          }}
        >
          {children}
        </DataProvider>
      </body>
    </html>
  );
}
