import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { DataProvider } from "@/context/DataContext";
import { loadAppData } from "@/lib/data";
import { GameContextProvider } from "@/context/GameContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const fetcheddata = await loadAppData();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GameContextProvider>
          <DataProvider
            value={{
              regions: fetcheddata.regions,
              countries: fetcheddata.countries,
              countryprovinces: fetcheddata.countryprovinces,
              paths: fetcheddata.paths,
              emptylands: fetcheddata.emptylands,
              areapaths: fetcheddata.areapaths,
              countryoutlines: fetcheddata.countryoutlines,
              terraincolors: fetcheddata.terraincolors,
              regionnames: fetcheddata.regionnames,
              countryplace: fetcheddata.countryplaces,
            }}
          >
            {children}
          </DataProvider>
        </GameContextProvider>
      </body>
    </html>
  );
}
